final_project/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();


// Route::group(['middleware' => ['auth','cekrole:petugas']], function(){
Route::resource('kategori','KategoriController')->except(['delete']);
Route::get('kategori/delete/{kategori}', 'KategoriController@destroy')->name('kategori.delete');
Route::resource('penerbit','PenerbitController')->except(['delete']);
Route::get('penerbit/delete/{penerbit}', 'PenerbitController@destroy')->name('penerbit.delete');
Route::resource('buku','BukuController')->except(['delete']);
Route::get('buku/delete/{buku}', 'BukuController@destroy')->name('buku.delete');
Route::resource('dashadmin','DashAdminController');
Route::resource('member','MemberController');
// });

// Route::group(['middleware' => ['auth','cekrole:member']], function(){
Route::get('/home', 'UserDashboardController@index')->name('home');
#dashboard route
Route::get('/dashboard', 'UserDashboardController@index')->name('dashboard.index');
Route::get('/dashboard/{id}/show', 'UserDashboardController@show');
Route::put('/dashboard/{id}/komen', 'KomentarBukuController@update');
Route::get('/dashboard/cari', 'UserDashboardController@cari');
Route::post('/dashboard/{id}/download', 'UserDashboardController@downloadfile');

#profile route
Route::get('/profil', 'ProfilController@index')->name('profil.index');
Route::put('/profil/{id}', 'ProfilController@update');
Route::put('/profil/{id}/updatefoto', 'ProfilController@updatefoto');

#koleksi route
Route::resource('/koleksi','KoleksiController')->except(['store']);
Route::post('/koleksi/{id}/add', 'KoleksiController@store')->name('add.book');
Route::post('/koleksi/{id}/view', 'KoleksiController@show');

#histori route
Route::resource('/histori','HistoriController');

// });

final_project/app/Buku.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Buku extends Model
{
    public function kategori(){
        return $this->belongsTo('App\Kategori');
    }
    public function penerbit(){
        return $this->belongsTo('App\Penerbit');
    }
    public function user(){
        return $this->belongsToMany('App\User');
    }
    public function komentar_buku(){
        return $this->hasMany('App\Komentar_buku');
    }
    protected $table = 'bukus';
    protected $guarded = [];
}

final_project/app/Http/Controllers/BukuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Buku;
use App\Penerbit;
use App\Kategori;
class BukuController extends Controller
{
    public function __construct()
        {
         $this->middleware('auth');   // jika ingin beberapa yg di auth menggunakan only([])
        }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $buku = Buku::with('kategori','penerbit')->orderBy('id','DESC')->get();
         return view('buku/index', compact('buku'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kat = Kategori::all();
        $pen = Penerbit::all();
        return view('buku.create', compact('kat','pen'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $request->validate([
            'judul' => 'required|unique:bukus',
            'deskripsi' => 'required',
            'penulis' => 'required',
            'tahun' => 'required',
            'sampul' => 'required|mimes: jpeg,jpg,png| max:2048',
            'file' => 'required|mimes:pdf| max:5000'
        ]);
        $imgName = $request->judul. '-' . time() . '.' . $request->sampul->extension(); 
        $request->sampul->move(public_path('image'), $imgName);

        $bukuName = $request->judul. '-' . time() . '.' . $request->file->extension(); 
        $request->file->move(public_path('book'), $bukuName);

        $buku = Buku::create([
                "judul" => $request['judul'],
                'deskripsi' => $request['deskripsi'],
                'penulis' => $request['penulis'],
                'tahun' => $request['tahun'],
                'kategori_id' => $request['kategori_id'],
                'penerbit_id' => $request['penerbit_id'],
                'sampul' => $imgName,
                'file' => $bukuName
            ]);
        return redirect()->route('buku.index')->with('success','Data Buku Berhasil Disimpan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $buku = Buku::find($id);
        
        return view('buku/show',compact('buku'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $buku = Buku::find($id);
        $kat = Kategori::all();
        $pen = Penerbit::all();
        return view('buku/edit', compact('buku','kat','pen'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $buku = Buku::find($id);
        $request->validate([
                'judul' => 'required',
                'deskripsi' => 'required',
                'penulis' => 'required',
                'tahun' => 'required',
                ]);

        if($request->sampul != ''){        
            $path = public_path('image/');

            //code for remove old file
            if($buku->sampul != ''  && $buku->sampul != null){
                $file_old = $path.$buku->sampul;
                unlink($file_old);
            }

            //upload new file
            $file = $request->sampul;
            $filename = $file->getClientOriginalName();
            $file->move($path, $filename);


           $buku->update([
                'judul' => $request['judul'],
                'deskripsi' => $request['deskripsi'],
                'penulis' => $request['penulis'],
                'tahun' => $request['tahun'],
                'sampul' => $filename
                   
            ]);

            
        }elseif($request->file != ''){

        $path = public_path('book/');

        //code for remove old file
        if($buku->file != ''  && $buku->file != null){
            $file_old = $path.$buku->file;
            unlink($file_old);
        }

        //upload new file
        $files = $request->file;
        $filename = $files->getClientOriginalName();
        $files->move($path, $filename);


        $buku->update([
            'judul' => $request['judul'],
            'deskripsi' => $request['deskripsi'],
            'penulis' => $request['penulis'],
            'tahun' => $request['tahun'],
            'file' => $filename
        ]);
    }else{
        $buku->update([
            'judul' => $request['judul'],
            'deskripsi' => $request['deskripsi'],
            'penulis' => $request['penulis'],
            'tahun' => $request['tahun'],
       ]);

            
    }
    return redirect()->route('buku.index')->with('success','Berhasil Di Ubah!');
}

   

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $buku = Buku::destroy($id);
        return redirect()->route('buku.index')->with('success','Berhasil Di Dihapus!');
    }
}

final_project/resources/views/buku/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="ml-3 pt-5 mr-3">
 <div class="card card-primary ">
            <div class="card-header with-border ">
              <h3 class="card-title ">Buat Data Buku</h3>
            </div>
            
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{route('buku.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
              <div class="box-body">
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Judul Buku</label>
                  <input type="text" class="form-control" id="judul" name="judul"  value="{{ old('judul','') }}" placeholder="Masukkan Judul Buku">
                    @error('judul')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
                 <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Deskripsi</label>
                  <textarea class="form-control" rows="3" id="deskripsi" name="deskripsi" value="{{ old('deskripsi','') }}" placeholder="Masukkan Deskripsi Buku"></textarea>
                    @error('deskripsi')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
                 <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Penulis</label>
                  <input type="text" class="form-control" id="penulis" name="penulis"  value="{{ old('penulis','') }}" placeholder="Masukkan Penulis Buku">
                    @error('penulis')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
                 <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Tahun Buku</label>
                  <input type="text" class="form-control" id="tahun" name="tahun"  value="{{ old('tahun','') }}" placeholder="Masukkan Tahun Buku">
                    @error('tahun')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
                <div class="form-group ml-3 mr-3 mt-3">

                  <label for="exampleInputEmail1">Kategori</label>  
                  <select name="kategori_id" id="kategori_id" class="form-control" >
                    <option disabled value>Pilih Kategori</option>
                    @foreach ($kat as $kt)
                        <option value="{{ $kt->id }}">{{ $kt->nama }}</option>
                    @endforeach
                    
                  </select>
                    @error('kategori_id')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Penerbit</label>  
                  <select name="penerbit_id" id="penerbit_id" class="form-control" >
                    <option disabled value>Pilih Penerbit</option>
                    @foreach ($pen as $item)
                        <option value="{{ $item->id }}">{{ $item->nama }}</option>
                    @endforeach
                    
                  </select>
                    @error('penerbit_id')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
                 <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Upload Sampul</label>
                  <input type="file" class="form-control-file" id="sampul" name="sampul" accept="image/*" >
                    @error('sampul')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                 <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Upload Buku</label>
                   <input type="file" class="form-control-file" id="file" name="file" accept="application/pdf">
                    @error('file')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
              </div>
              <!-- /.box-body -->
              <div class="box-footer text-right  ml-3 mr-3 mb-3">
                <a href="{{route('buku.index')}}" class="btn btn-default ml-3">Kembali</a>
                <button type="submit" class="btn btn-primary ml-3">Submit</button>
              </div>
            </form>
          </div>
</div>
@endsection

final_project/resources/views/buku/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="ml-3 pt-3 mt-3">
 <div class="card card-primary ">
            <div class="card-header with-border ">
              <h3 class="card-title ">Ubah Data Buku </h3>
            </div>
            
            <!-- /.box-header -->
            <!-- form start -->
          <form role="form" action="{{route('buku.update',['buku'=> $buku->id ])}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
              <div class="box-body">
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Judul Buku</label>
                  <input type="text" class="form-control" id="judul" name="judul"  value="{{ old('judul', $buku->judul) }}" placeholder="Masukkan Judul">
                    @error('judul')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group ml-3 mr-3">
                  <label for="exampleInputPassword1">Deskripsi</label>
                  <input class="form-control" rows="3" id="deskripsi" name="deskripsi" value="{{ old('deskripsi', $buku->deskripsi) }}" placeholder="Masukkan Deskripsi"></input>
                  @error('deskripsi')
                      <div class="alert alert-danger">{{ $message }}</div>
                  @enderror
                </div>
                 <div class="form-group ml-3 mr-3">
                  <label for="exampleInputPassword1">Penulis</label>
                  <input class="form-control" rows="3" id="penulis" name="penulis" value="{{ old('penulis', $buku->penulis) }}" placeholder="Masukkan Penulis"></input>
                  @error('penulis')
                      <div class="alert alert-danger">{{ $message }}</div>
                  @enderror
                </div>
                 <div class="form-group ml-3 mr-3">
                  <label for="exampleInputPassword1">Tahun</label>
                  <input class="form-control" rows="3" id="tahun" name="tahun" value="{{ old('tahun', $buku->tahun) }}" placeholder="Masukkan Tahun"></input>
                  @error('tahun')
                      <div class="alert alert-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group ml-3 mr-3 mt-3">

                    <label for="exampleInputEmail1">Kategori</label>  
                    <select name="kategori_id" id="kategori_id" class="form-control" >
                      <option disabled value>Pilih Kategori</option>
                      @foreach ($kat as $kt)
                          <option value="{{ $kt->id }}" @if($buku->kategori_id == $kt->id ) selected @endif>{{ $kt->nama }}</option>
                      @endforeach
                      
                    </select>
                      @error('kategori_id')
                          <div class="alert alert-danger">{{ $message }}</div>
                      @enderror
                  </div> 
                  <div class="form-group ml-3 mr-3 mt-3">
                    <label for="exampleInputEmail1">Penerbit</label>  
                    <select name="penerbit_id" id="penerbit_id" class="form-control" >
                      <option disabled value>Pilih Penerbit</option>
                      @foreach ($pen as $item)
                          <option value="{{ $item->id }}" @if($buku->penerbit_id == $item->id ) selected @endif>{{ $item->nama }}</option>
                      @endforeach
                      
                    </select>
                      @error('penerbit_id')
                          <div class="alert alert-danger">{{ $message }}</div>
                      @enderror
                  </div> 
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Upload Sampul</label>
                  <input type="file" class="form-control-file mb-2" id="sampul" name="sampul" accept="image/*">
                  <img src="{{ asset('image/'. $buku->sampul) }}" width="200">
                    @error('sampul')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Upload Buku</label>
                   <input type="text" class="form-control-file mb-2 col-2" disabled id="file" name="file" value="{{ $buku->file }}"  accept="application/pdf">
                   <input type="file" class="form-control-file" id="file" name="file">
                    @error('file')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
              </div>
              <!-- /.box-body -->
              <div class="box-footer text-right  ml-3 mr-3 mb-3">
                <a href="{{route('buku.index')}}" class="btn btn-default ml-3">Kembali</a>
                <button type="submit" class="btn btn-primary ml-3">Submit</button>
              </div>
            </form>
          </div>
</div>
   
@endsection

final_project/resources/views/buku/index.blade.php
@extends('layouts.master')


@section('content')
     <div class="ml-3 pt-5 mr-3">
        <div class="card card-primary">
            <div class="card-header with-border">
              <h3 class="card-title">Table Data Buku</h3>
            </div>
            <!-- /.box-header -->
            <div class="card-body">
              @if(session('success')) 
                <div class="alert alert-success">
                  {{ session('success') }}
                </div>
              @endif
              <a href="{{ route("buku.create") }}" class="btn btn-primary mt-2 mb-3">Buat Data Buku</a>
              <table class="table table-bordered" id="example">
                <thead class="bg-dark text-light"><tr>
                  <th style="width: 10px">No</th>
                  <th>Judul Buku</th>
                  <th>Penulis</th>
                  <th>Sampul</th>
                  <th style="width: 40px">Actions</th>
                </tr></thead>
                <tbody>
                @forelse ($buku as $key => $bk)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $bk->judul }}</td>
                    <td>{{ $bk->penulis }}</td>
                    <td class="text-center"><img src="/image/{{ $bk->sampul }}" alt="Sampul {{ $bk->judul }}" width="50px"></td>
                    <td style="display: flex">
                      <a href="{{route('buku.show',['buku' => $bk->id] )}}" class="btn btn-info btn-sm m-sm-1 " >Show</a>
                      <a href="{{route('buku.edit',['buku' => $bk->id] )}}" class="btn btn-success btn-sm m-sm-1">Edit</a>
                      <a href="{{route('buku.delete',['buku' => $bk->id] )}}" class="btn btn-danger btn-sm m-sm-1 button delete-confirm">Delete</a>
             
                      
                    </td>
                </tr>    
                @empty
                <tr>
                  <td colspan ="4" align="center">Belum ada Data Buku</td>
                </tr>
                @endforelse
                </tbody>
              
               
              </table>
            </div>
            <!-- /.box-body -->
            
          </div>
    </div>
@endsection

@push('script')
  <script type="text/javascript" src="{{ asset('assets/js/sweetalert.js') }}"></script>
  <script>
      $(document).ready(function() {
        $('#example').DataTable();
      } );
    </script>
@endpush

final_project/resources/views/buku/show.blade.php
@extends('layouts.master')

@section('content')

<div class="container-fluid">
      <div class="ml-3 pt-5 mr-3">
          <div class="row">
              <div class="col-lg-4 sm-12">
                  <div class="card">
                      <div class="card-body">
                          <h4 class="d-flex justify-content-center">Sampul Buku</h4>
                          <hr>
                          <img class="img-fluid rounded" src="{{ asset('image/'.$buku->sampul)}}" alt="">
                          <hr>
                          <center>
                            <form method="POST" action="/dashboard/{{$buku->id}}/download" target="_blank">
                            @csrf
                                <button type="submit" name="submit" class="btn btn-primary rounded mx-auto d-block"></i>Baca Buku </button>
                            </form>
                          </center>
                     </div>
                  </div>
              </div>
              <div class="col-lg-8 sm-12">
                  <div class="card">
                      <div class="card-body">
                          <h4 class="d-flex justify-content-center">Informasi Buku</h4>
                          <hr>
                          <form action="{{route('add.book',['id' => $buku->id])}}" method="POST">
                              @csrf
                              <div class="form-group">
                                      <label for="judul">Judul Buku : </label>
                                      <input type="text" readonly class="form-control" id="judul" name="judul" value="{{$buku->judul}}">  
                              </div>
  
                              <div class="form-group">
                                      <label for="deskripsi">Deskripsi Buku : </label>
                                      <textarea id="deskripsi" class="form-control" readonly name="desk" rows="4" style="resize:none;">{{$buku->deskripsi}}</textarea>            
                              </div>
                              <div class="form-group row">
                                  <div class="col-sm-6">
                                          <label for="penulis">Penulis Buku : </label>
                                          <input type="text" readonly class="form-control" id="penulis" name="penulis" value="{{$buku->penulis}}">
                                      </div>
                                  <div class="col-sm-6">
                                          <label for="tahun">Tahun Release Buku : </label>
                                          <input type="text" readonly class="form-control" id="tahun" name="tahun" value="{{$buku->tahun}}">
                                  </div>
                              </div>
                              <div class="form-group row">
                                  <div class="col-sm-6">
                                          <label for="kategori">Kategori Buku : </label>
                                          <input type="text" readonly class="form-control" id="kategori" name="kategori" value="{{$buku->kategori->nama}}">
                                  </div>
                                  <div class="col-sm-6">
                                      <label for="penerbit">Penerbit Buku : </label>
                                      <input type="text" readonly class="form-control" id="penerbit" name="penerbit" value="{{$buku->penerbit->nama}}">
                                  </div>
                              </div>
                              <div class="box-footer text-right  ml-3 mb-3">
                                  <a href="/buku" class="btn btn-primary ml-3">Kembali</a>
                              </div>
                          </form>
                      </div>
                  </div>
              </div>
          </div>
      </div>
</div>


@endsection