final_project/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();


// Route::group(['middleware' => ['auth','cekrole:petugas']], function(){
Route::resource('kategori','KategoriController')->except(['delete']);
Route::get('kategori/delete/{kategori}', 'KategoriController@destroy')->name('kategori.delete');
Route::resource('penerbit','PenerbitController')->except(['delete']);
Route::get('penerbit/delete/{penerbit}', 'PenerbitController@destroy')->name('penerbit.delete');
Route::resource('buku','BukuController')->except(['delete']);
Route::get('buku/delete/{buku}', 'BukuController@destroy')->name('buku.delete');
Route::resource('dashadmin','DashAdminController');
Route::resource('member','MemberController');
// });

// Route::group(['middleware' => ['auth','cekrole:member']], function(){
Route::get('/home', 'UserDashboardController@index')->name('home');
#dashboard route
Route::get('/dashboard', 'UserDashboardController@index')->name('dashboard.index');
Route::get('/dashboard/{id}/show', 'UserDashboardController@show');
Route::put('/dashboard/{id}/komen', 'KomentarBukuController@update');
Route::get('/dashboard/cari', 'UserDashboardController@cari');
Route::post('/dashboard/{id}/download', 'UserDashboardController@downloadfile');

#profile route
Route::get('/profil', 'ProfilController@index')->name('profil.index');
Route::put('/profil/{id}', 'ProfilController@update');
Route::put('/profil/{id}/updatefoto', 'ProfilController@updatefoto');

#koleksi route
Route::resource('/koleksi','KoleksiController')->except(['store']);
Route::post('/koleksi/{id}/add', 'KoleksiController@store')->name('add.book');
Route::post('/koleksi/{id}/view', 'KoleksiController@show');

#histori route
Route::resource('/histori','HistoriController');

// });

final_project/app/Penerbit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Penerbit extends Model
{
    protected $table = "penerbits";
    protected $guarded = [];
    public function buku()
     {
         return $this->hasOne('App\Buku');
     }
}

final_project/app/Http/Controllers/PenerbitController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Penerbit;
use DB;
class PenerbitController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');   // jika ingin beberapa yg di auth menggunakan only([])
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $penerbit = Penerbit::orderBy('id','DESC')->get();
         return view('penerbit/index', compact('penerbit'));
    }
    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('penerbit.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
                'nama' => 'required|unique:penerbits',
                'no_telp' =>'required',
                'alamat' =>'required'
            ]);
        $penerbit = Penerbit::create([
                   "nama" => $request['nama'],
                   "no_telp" => $request['no_telp'],
                   "alamat" => $request['alamat']
               ]);
        return redirect()->route('penerbit.index')->with('success','Penerbit Berhasil Disimpan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $penerbit = Penerbit::find($id);
        
        return view('penerbit/show',compact('penerbit'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $penerbit = Penerbit::find($id);
         return view('penerbit/edit', compact('penerbit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
                'nama' => 'required|unique:penerbits',
                'no_telp' =>'required',
                'alamat' =>'required'
                ]);
        $penerbit = Penerbit::where('id',$id)->update([
                     "nama" => $request['nama'],
                     "no_telp" => $request['no_telp'],
                     "alamat" => $request['alamat']
         ]);

        return redirect()->route('penerbit.index')->with('success','Berhasil Di Ubah!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $penerbit = Penerbit::destroy($id);
        return redirect()->route('penerbit.index')->with('success','Berhasil Di Dihapus!');
    }
}

final_project/resources/views/penerbit/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="ml-3 pt-5 mr-3">
 <div class="card card-primary ">
            <div class="card-header with-border ">
              <h3 class="card-title ">Buat Data Penerbit Buku</h3>
            </div>
            
            <!-- /.box-header -->
            <!-- form start -->
          <form role="form" action="{{route('penerbit.store')}}" method="POST">
                @csrf
              <div class="box-body">
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Nama Penerbit</label>
                  <input type="text" class="form-control" id="nama" name="nama"  value="{{ old('nama','') }}" placeholder="Masukkan Nama Penerbit">
                    @error('nama')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Nomer Telepon</label>
                  <input type="text" class="form-control" id="no_telp" name="no_telp"  value="{{ old('no_telp','') }}" placeholder="Masukkan Nomor Telepon">
                    @error('no_telp')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Alamat</label>
                  <input type="text" class="form-control" id="alamat" name="alamat"  value="{{ old('alamat','') }}" placeholder="Masukkan Alamat">
                    @error('alamat')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
              </div>
              <!-- /.box-body -->
              <div class="box-footer text-right  ml-3 mr-3 mb-3">
                <a href="{{route('penerbit.index')}}" class="btn btn-default ml-3">Kembali</a>
                <button type="submit" class="btn btn-primary ml-3">Submit</button>
              </div>
            </form>
          </div>
</div>
@endsection

final_project/resources/views/penerbit/edit.blade.php
@extends('layouts.master')


@section('content')
    <div class="ml-3 pt-5 mr-3">
 <div class="card card-primary ">
            <div class="card-header with-border ">
              <h3 class="card-title ">Ubah Data Penerbit </h3>
            </div>
            
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{route('penerbit.update',['penerbit'=> $penerbit->id])}}" method="POST">
                @csrf
                @method('PUT')
              <div class="box-body">
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Nama Penerbit</label>
                  <input type="text" class="form-control" id="nama" name="nama"  value="{{ old('nama',$penerbit->nama) }}" placeholder="Masukkan Nama Penerbit">
                    @error('nama')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Nomer Telepon</label>
                  <input type="text" class="form-control" id="no_telp" name="no_telp"  value="{{ old('no_telp',$penerbit->no_telp) }}" placeholder="Masukkan Nomor Telepon">
                    @error('no_telp')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Alamat</label>
                  <input type="text" class="form-control" id="alamat" name="alamat"  value="{{ old('alamat',$penerbit->alamat) }}" placeholder="Masukkan Alamat">
                    @error('alamat')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
              </div>
              <!-- /.box-body -->
              <div class="box-footer text-right  ml-3 mr-3 mb-3">
                <a href="{{route('penerbit.index')}}" class="btn btn-default ml-3">Kembali</a>
                <button type="submit" class="btn btn-primary ml-3">Submit</button>
              </div>
            </form>
          </div>
</div>
@endsection

final_project/resources/views/penerbit/index.blade.php
@extends('layouts.master')


@section('content')
     <div class="ml-3 pt-5 mr-3">
        <div class="card card-primary">
            <div class="card-header with-border">
              <h3 class="card-title">Table Data Penerbit</h3>
            </div>
            <!-- /.box-header -->
            <div class="card-body">
              @if(session('success')) 
                <div class="alert alert-success">
                  {{ session('success') }}
                </div>
              @endif
              <a href="{{ route("penerbit.create") }}" class="btn btn-primary mt-2 mb-3">Buat Data Penerbit</a>
              <table class="table table-bordered" id="example">
                <thead class="bg-dark text-light"><tr>
                  <th style="width: 10px">No</th>
                  <th>Nama Penerbit</th>
                  <th style="width: 40px">Actions</th>
                </tr></thead>
                <tbody>
                @forelse ($penerbit as $key => $pen)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $pen->nama }}</td>
                    <td style="display: flex">
                      <a href="{{route('penerbit.show',['penerbit' => $pen->id])}}" class="btn btn-info btn-sm m-sm-1">Show</a>
                      <a href="{{route('penerbit.edit',['penerbit' => $pen->id])}}" class="btn btn-success btn-sm m-sm-1">Edit</a>
                      <a href="{{route('penerbit.delete',['penerbit' => $pen->id])}}" class="btn btn-danger btn-sm m-sm-1 button delete-confirm">Delete</a>
              
                      
                    </td>
                </tr>    
                @empty
                <tr>
                  <td colspan ="4" align="center">Belum ada Data Penerbit</td>
                </tr>
                @endforelse
                </tbody>
              
               
              </table>
            </div>
            <!-- /.box-body -->
            
          </div>
    </div>
@endsection

@push('script')
  <script type="text/javascript" src="{{ asset('assets/js/sweetalert.js') }}"></script>
  <script>
      $(document).ready(function() {
        $('#example').DataTable();
      } );
    </script>
@endpush

final_project/resources/views/penerbit/show.blade.php
@extends('layouts.master')

@section('content')
    <div class="ml-3 pt-5 mr-3">
 <div class="card card-primary ">
            <div class="card-header with-border ">
              <h3 class="card-title ">Show Data Penerbit Buku</h3>
            </div>
            
            <!-- /.box-header -->
            <!-- form start -->
          <form role="form" action="{{route('penerbit.store')}}" method="POST">
                @csrf
              <div class="box-body">
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Nama Penerbit</label>
                  <input type="text" class="form-control" id="nama" name="nama"  value="{{ $penerbit->nama }}" readonly placeholder="Masukkan Nama Penerbit">
                    @error('nama')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Nomer Telepon</label>
                  <input type="text" class="form-control" id="no_telp" name="no_telp"  value="{{ $penerbit->no_telp }}" readonly placeholder="Masukkan Nomor Telepon">
                    @error('no_telp')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Alamat</label>
                  <input type="text" class="form-control" id="alamat" name="alamat"  value="{{ $penerbit->alamat }}" readonly placeholder="Masukkan Alamat">
                    @error('alamat')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
              </div>
              <!-- /.box-body -->
              <div class="box-footer text-right  ml-3 mr-3 mb-3">
                <a href="{{route('penerbit.index')}}" class="btn btn-default ml-3">Kembali</a>
               </div>
            </form>
          </div>
</div>
@endsection