final_project/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();


// Route::group(['middleware' => ['auth','cekrole:petugas']], function(){
Route::resource('kategori','KategoriController')->except(['delete']);
Route::get('kategori/delete/{kategori}', 'KategoriController@destroy')->name('kategori.delete');
Route::resource('penerbit','PenerbitController')->except(['delete']);
Route::get('penerbit/delete/{penerbit}', 'PenerbitController@destroy')->name('penerbit.delete');
Route::resource('buku','BukuController')->except(['delete']);
Route::get('buku/delete/{buku}', 'BukuController@destroy')->name('buku.delete');
Route::resource('dashadmin','DashAdminController');
Route::resource('member','MemberController');
// });

// Route::group(['middleware' => ['auth','cekrole:member']], function(){
Route::get('/home', 'UserDashboardController@index')->name('home');
#dashboard route
Route::get('/dashboard', 'UserDashboardController@index')->name('dashboard.index');
Route::get('/dashboard/{id}/show', 'UserDashboardController@show');
Route::put('/dashboard/{id}/komen', 'KomentarBukuController@update');
Route::get('/dashboard/cari', 'UserDashboardController@cari');
Route::post('/dashboard/{id}/download', 'UserDashboardController@downloadfile');

#profile route
Route::get('/profil', 'ProfilController@index')->name('profil.index');
Route::put('/profil/{id}', 'ProfilController@update');
Route::put('/profil/{id}/updatefoto', 'ProfilController@updatefoto');

#koleksi route
Route::resource('/koleksi','KoleksiController')->except(['store']);
Route::post('/koleksi/{id}/add', 'KoleksiController@store')->name('add.book');
Route::post('/koleksi/{id}/view', 'KoleksiController@show');

#histori route
Route::resource('/histori','HistoriController');

// });

final_project/app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    protected $table = 'kategoris';
     protected $guarded = [];

     public function buku()
     {
         return $this->hasOne('App\Buku');
     }
}

final_project/app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Kategori;
use Auth;
use DB;

class KategoriController extends Controller
{
    public function __construct()
        {
         $this->middleware('auth');   // jika ingin beberapa yg di auth menggunakan only([])
        }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kategori = Kategori::orderBy('id','DESC')->get();
        return view('kategori/index', compact('kategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $request->validate([
                'nama' => 'required|unique:kategoris'
            ]);
             $kategori = Kategori::create([
                        "nama" => $request['nama']
                    ]);
            return redirect()->route('kategori.index')->with('success','Kategori Berhasil Disimpan!');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $kategori = Kategori::find($id);
        
        return view('kategori/show',compact('kategori'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategori = Kategori::find($id);
        return view('kategori/edit', compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $request->validate([
                    'nama' => 'required'
                ]);
           $kategori = Kategori::where('id',$id)->update([
                    "nama"=>$request['nama']
            ]);

            return redirect()->route('kategori.index')->with('success','Berhasil Di Ubah!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kategori = Kategori::destroy($id);
        return redirect()->route('kategori.index')->with('success','Berhasil Di Dihapus!');
    }
}

final_project/resources/views/kategori/create.blade.php
@extends('layouts.master')

@section('content')
<div class="ml-3 pt-5 mr-3">
 <div class="card card-primary ">
            <div class="card-header with-border ">
              <h3 class="card-title ">Buat Kategori Buku</h3>
            </div>
            
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{route('kategori.store')}}" method="POST">
                @csrf
              <div class="box-body">
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Nama Kategori</label>
                  <input type="text" class="form-control" id="nama" name="nama"  value="{{ old('nama','') }}" placeholder="Masukkan Kategori">
                    @error('nama')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div> 
              </div>
              <!-- /.box-body -->
              <div class="box-footer text-right  ml-3 mr-3 mb-3">
                <a href="{{route('kategori.index')}}" class="btn btn-default ml-3">Kembali</a>
                <button type="submit" class="btn btn-primary ml-3">Submit</button>
              </div>
            </form>
          </div>
</div>
@endsection

final_project/resources/views/kategori/edit.blade.php
@extends('layouts.master')


@section('content')
    <div class="ml-3 pt-5 mr-3">
 <div class="card card-primary ">
            <div class="card-header with-border ">
              <h3 class="card-title ">Ubah Kategori </h3>
            </div>
            
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{route('kategori.update',['kategori'=> $kategori->id])}}" method="POST">
                @csrf
                @method('PUT')
              <div class="box-body">
                <div class="form-group ml-3 mr-3 mt-3">
                  <label for="exampleInputEmail1">Nama Kategori</label>
                  <input type="text" class="form-control" id="nama" name="nama"  value="{{ old('nama', $kategori->nama) }}" placeholder="Masukkan Nama">
                    @error('nama')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer text-right  ml-3 mr-3 mb-3">
                  <a href="{{route('kategori.index')}}" class="btn btn-default ml-3">Kembali</a>
                <button type="submit" class="btn btn-primary ml-3">Submit</button>
              </div>
            </form>
          </div>
</div>
@endsection

final_project/resources/views/kategori/index.blade.php
@extends('layouts.master')


@section('content')
     <div class="ml-3 pt-5 mr-3">
        <div class="card card-primary">
            <div class="card-header with-border">
              <h3 class="card-title">Table Kategori</h3>
            </div>
            <!-- /.box-header -->
            <div class="card-body">
              @if(session('success')) 
                <div class="alert alert-success">
                  {{ session('success') }}
                </div>
              @endif
              <a href="{{ route("kategori.create") }}" class="btn btn-primary mt-2 mb-3">Buat Kategori</a>
              <table class="table table-bordered" id="example">
                <thead class="bg-dark text-light"><tr>
                  <th style="width: 10px">No</th>
                  <th>Nama Kategori</th>
                  <th style="width: 40px">Actions</th>
                </tr></thead>
                <tbody>
                @forelse ($kategori as $key => $kat)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $kat->nama }}</td>
                    <td style="display: flex">
                      <a href="{{route('kategori.show',['kategori'=> $kat->id])}}" class="btn btn-info btn-sm m-sm-1">Show</a>
                      <a href="{{route('kategori.edit',['kategori'=> $kat->id])}}" class="btn btn-success btn-sm m-sm-1">Edit</a>
                      <a href="{{route('kategori.delete',['kategori'=> $kat->id])}}" class="btn btn-danger btn-sm m-sm-1 button delete-confirm">Delete</a>  
                    </td>
                </tr>    
                @empty
                <tr>
                  <td colspan ="4" align="center">Belum ada Kategori</td>
                </tr>
                @endforelse
                </tbody>
              
               
              </table>
            </div>
            <!-- /.box-body -->
            
          </div>
    </div>
@endsection

@push('script')
  <script type="text/javascript" src="{{ asset('assets/js/sweetalert.js') }}"></script>
  <script>
    $(document).ready(function() {
      $('#example').DataTable();
    } );
  </script>
@endpush

final_project/resources/views/kategori/show.blade.php
@extends('layouts.master')

@section('content')

<div class="ml-3 pt-5 mr-3">
   <div class="card card-primary ">
              <div class="card-header with-border ">
                <h3 class="card-title ">Show Kategori Buku</h3>
              </div> 
              <!-- /.box-header -->
              <!-- form start -->
              <form role="form" action="#" method="POST">
                @csrf
                <div class="box-body">
                  <div class="form-group ml-3 mr-3 mt-3">
                    <label for="exampleInputEmail1">Nama Kategori</label>
                    <input type="text" class="form-control" id="nama" name="nama"  value="{{ $kategori->nama }}" placeholder="Masukkan Kategori" readonly>
                      @error('nama')
                          <div class="alert alert-danger">{{ $message }}</div>
                      @enderror
                  </div> 
                </div>
                <!-- /.box-body -->
                <div class="box-footer text-right  ml-3 mr-3 mb-3">
                <a href="{{route('kategori.index')}}" class="btn btn-default ml-3">Kembali</a>
                </div>
              </form>
            </div>
  </div>

@endsection