final_project/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();


// Route::group(['middleware' => ['auth','cekrole:petugas']], function(){
Route::resource('kategori','KategoriController')->except(['delete']);
Route::get('kategori/delete/{kategori}', 'KategoriController@destroy')->name('kategori.delete');
Route::resource('penerbit','PenerbitController')->except(['delete']);
Route::get('penerbit/delete/{penerbit}', 'PenerbitController@destroy')->name('penerbit.delete');
Route::resource('buku','BukuController')->except(['delete']);
Route::get('buku/delete/{buku}', 'BukuController@destroy')->name('buku.delete');
Route::resource('dashadmin','DashAdminController');
Route::resource('member','MemberController');
// });

// Route::group(['middleware' => ['auth','cekrole:member']], function(){
Route::get('/home', 'UserDashboardController@index')->name('home');
#dashboard route
Route::get('/dashboard', 'UserDashboardController@index')->name('dashboard.index');
Route::get('/dashboard/{id}/show', 'UserDashboardController@show');
Route::put('/dashboard/{id}/komen', 'KomentarBukuController@update');
Route::get('/dashboard/cari', 'UserDashboardController@cari');
Route::post('/dashboard/{id}/download', 'UserDashboardController@downloadfile');

#profile route
Route::get('/profil', 'ProfilController@index')->name('profil.index');
Route::put('/profil/{id}', 'ProfilController@update');
Route::put('/profil/{id}/updatefoto', 'ProfilController@updatefoto');

#koleksi route
Route::resource('/koleksi','KoleksiController')->except(['store']);
Route::post('/koleksi/{id}/add', 'KoleksiController@store')->name('add.book');
Route::post('/koleksi/{id}/view', 'KoleksiController@show');

#histori route
Route::resource('/histori','HistoriController');

// });

final_project/app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Profil;

class MemberController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');   // jika ingin beberapa yg di auth menggunakan only([])
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $member = User::where('role','member')->orderBy('id','DESC')->get();
        return view('members.index',compact('member'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $member = User::find($id);
        $profil = Profil::find($id);
        return view('members.show',compact('member','profil'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       if($request->approve === "approve"){
        $member = Profil::where('user_id',$id)->update([
            'is_active' => '1'
        ]);
       }
       elseif($request->approve === "reject"){
        $member = Profil::where('user_id',$id)->update([
            'is_active' => '0'
        ]);
       }
        
        return redirect()->route('member.index')->with('success','Berhasil Di Ubah!');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

final_project/resources/views/members/index.blade.php
@extends('layouts.master')


@section('content')
     <div class="ml-3 pt-5 mr-3">
        <div class="card card-primary">
            <div class="card-header with-border">
              <h3 class="card-title">Table Member</h3>
            </div>
            <!-- /.box-header -->
            <div class="card-body">
              @if(session('success')) 
                <div class="alert alert-success">
                  {{ session('success') }}
                </div>
              @endif
              <table class="table table-bordered" id="example">
                <thead class="bg-dark text-light"><tr>
                  <th style="width: 10px">No</th>
                  <th>Nama member</th>
                  <th>Email</th>
                  <th>Tanggal Daftar</th>
                  <th>Status</th>
                  <th style="width: 40px">Actions</th>
                </tr></thead>
                <tbody>
                @forelse ($member as $key => $data)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $data->name }}</td>
                    <td>{{ $data->email }}</td>
                    <td>{{ $data->created_at }}</td>
                    @if($data->profil->is_active == "0")
                    <td>{{ 'Tidak Aktif'}}</td>
                    @else
                    <td>{{ 'Aktif'}}</td>
                    @endif
                    <td style="display: flex">
                      <a href="{{route('member.show',['member' => $data->id ])}}" class="btn btn-info btn-sm m-sm-1">Show</a>
                      <form action="{{route('member.update',['member' => $data->id ])}}" method="POST">
                        @csrf
                        @method('PUT') 
                         @if($data->profil->is_active == 0)
                           <input type="submit" name="approve" value="approve" class="btn btn-success btn-sm m-sm-1">
                         @else
                           <input type="submit" name="approve" value="reject" class="btn btn-danger btn-sm m-sm-1">
                         @endif
                       </form>
                      
                    </td>
                </tr>    
                @empty
                <tr>
                  <td colspan ="4" align="center">Belum ada member</td>
                </tr>
                @endforelse
                </tbody>
              
               
              </table>
            </div>
            <!-- /.box-body -->
            
          </div>
    </div>
@endsection

@push('script')

  <script>
    $(document).ready(function() {
      $('#example').DataTable();
    } );
  </script>
    
@endpush

final_project/resources/views/members/show.blade.php
@extends('layouts.master')

@section('content')
<div class="container-fluid">
    <div class="ml-3 pt-5 mr-3">
        <div class="row">
            <div class="col-lg-4 sm-12">
                <div class="card">
                    <div class="card-body">
                        <img class="img-fluid rounded" style="width: 100%;" src="{{ asset('assets/images/Foto Profile/'.$profil->foto)}}" alt="">
                        <hr>
                         <center>
                         <a class="btn btn-primary rounded mx-auto d-block" href="{{route('member.index')}}"> Kembali </a>
                         </center>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 sm-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="d-flex justify-content-center">Profil Member</h4>
                        <hr>
                        @if (session('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                        @endif
                        <form class="form-group" method="POST" action="#">
                        @method('PUT')
                        @csrf
                            <label for="nama">Nama Lengkap : </label>
                            <input type="text" class="form-control" id="nama" name="nama" value="{{ $profil->nama}}">
                            <label for="nik">NIK : </label>
                            <input type="text" class="form-control" id="nik" name="nik" value="{{ $profil->nik}}">
                            <label for="alamat">Alamat : </label>
                            <textarea id="alamat" class="form-control" name="alamat" rows="2" style="resize: none;">{{$profil->alamat}}</textarea>
                            <label for="jk">Jenis Kelamin :</label>
                            <input type="text" class="form-control" id="jk" name="jenis_kelamin" value="{{$profil->jenis_kelamin}}">
                            <label for="telp">No. Telp :</label>
                            <input type="text" class="form-control" id="telp" name="telp" value="{{$profil->telp}}">
                      
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection